#!/bin/bash
logfile="/home/$USER/Downloads/bkup.txt"

if [ ! -f $logfile ]; then
	touch $logfile
elif [ -f $logfile ]; then
	rm $logfile
	touch $logfile
fi

bkup(){
	sleep 5s
	source=$(hostname)
	datestmp=$(date +"%Y-%m-%d")
	fname="backup_"$source"_"$datestmp

	tar --exclude='/home/$USER/github' \
	--exclude='/home/$USER/Downloads' \
	--exclude='/home/$USER/.*' \
	-czf ~/Downloads/$fname.tar.gzip ~/
	ls ~/Downloads/*.gzip
	echo "backup completed" >> $logfile

	scp ~/Downloads/$fname.tar.gzip \
		root@[2001:19f0:5:2548:5400:03ff:fedd:5a98]:/home/DropBox/
	echo "copy to offsite complete" >> $logfile
}
bkup
