#!/bin/bash

########################################
#Script to turn off Bluetooth on demand#
########################################

rdo() {
	if rfkill list bluetooth | grep -q 'yes$' ; then
		#rfkill unblock bluetooth
		rfkill block bluetooth
	else
		rfkill block bluetooth
	fi
}

rdo
exit
